<?php

namespace Helix\PostType;

abstract class PostType
{
    protected string $key;
    protected string $singular;
    protected string $plural;
    protected string $icon         = 'dashicons-admin-post';
    protected array  $supports     = ['title', 'editor', 'thumbnail'];
    protected bool   $public       = true;
    protected bool   $hasArchive   = true;
    protected int    $menuPosition = 5;
    protected array  $rewrite      = [];
    protected array  $taxonomies   = [];
    protected array  $labels       = [];

    public function register(): void
    {
        register_post_type($this->key, $this->buildArgs());
        $this->registerTaxonomies();
        $this->boot();
    }

    // Override to add hooks, AJAX handlers, etc.
    public function boot(): void {}

    protected function buildArgs(): array
    {
        return [
            'label'         => $this->plural,
            'labels'        => $this->buildLabels(),
            'public'        => $this->public,
            'has_archive'   => $this->hasArchive,
            'supports'      => $this->supports,
            'menu_icon'     => $this->icon,
            'menu_position' => $this->menuPosition,
            'rewrite'       => !empty($this->rewrite)
                                ? $this->rewrite
                                : ['slug' => $this->key],
            'show_in_rest'  => true,
        ];
    }

    protected function buildLabels(): array
    {
        // Only set labels that WP core has proper translated format strings for.
        // Everything else is auto-generated by WP's get_post_type_labels() —
        // developer should override via $labels for non-English sites.
        $defaults = [
            'name'          => $this->plural,
            'singular_name' => $this->singular,
            'menu_name'     => $this->plural,
            'add_new_item'  => __('Add New') . ' ' . $this->singular,
        ];

        return array_merge($defaults, $this->labels);
    }

    protected function registerTaxonomies(): void
    {
        foreach ($this->taxonomies as $taxKey => $config) {
            $singular = $config['singular']     ?? ucwords(str_replace('_', ' ', $taxKey));
            $plural   = $config['plural']       ?? $singular . 's';
            $hierarch = $config['hierarchical'] ?? true;
            $rewrite  = $config['rewrite']      ?? ['slug' => str_replace('_', '-', $taxKey)];

            register_taxonomy($taxKey, $this->key, [
                'label'        => $plural,
                'labels'       => $this->buildTaxLabels($singular, $plural),
                'hierarchical' => $hierarch,
                'rewrite'      => $rewrite,
                'show_in_rest' => true,
            ]);
        }
    }

    protected function buildTaxLabels(string $s, string $p): array
    {
        return [
            'name'          => $p,
            'singular_name' => $s,
            'menu_name'     => $p,
        ];
    }
}
